from .dr_science import *
from .elon import *
from .elon2 import *
from .cpp_coding import *
from .react_template import *
from .rewoo_template import *
from .openai_template import *
from .vanilla_template import *
from .openai_memory_template import *
from .vanilla-ziyu import *
from .scholar-ziyu import *
from .prakash_llm import *
from .prakash-llm import *
from .prakash-tool import *
from .prakash_scholar import *
from .prakash_scholar1 import *
from .prakash_scholar2 import *
from .prakash_scholar3 import *
